let _ = Printf.printf "0\n%!"
let _ = Ghc_misc.of_file "miner.ghc"
let _ = Printf.printf "1\n%!"
let _ = Ghc_misc.of_file "flipper.ghc"
let _ = Printf.printf "2\n%!"
let _ = Ghc_misc.of_file "frickle.ghc"
